In [2]:
# -*- coding: utf-8 -*-
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import scipy.stats as stats

Data prišli vo formáte, ktorom neboli dáta rozdelené ',', ale '\t' tabulátorom

In [9]:
measurments = pd.read_csv('./data/measurements.csv',delimiter='\t')
measurments

,longitude,CO,CFCs,NOx,warning,NH3,latitude,O3,Pb,H2CO,SO2,PM10,PAHs,C2H3NO5,CH4,TEMP,PM2.5,PRES
0,-76.43941,9.46865,74.15057,6.16649,1.0,8.82096,39.33427,8.15702,25.56370,43.82118,7.91673,7.81096,7.62246,4.53602,6.31769,17.89474,10.14740,1127.24291
1,37.49338,5.47663,63.61956,9.45736,1.0,7.82746,55.62047,6.30607,41.33842,62.73682,9.69317,6.97357,8.46427,4.00839,7.74927,36.75951,9.15325,1070.43456
2,122.05228,9.85715,55.88937,9.22296,0.0,7.18582,37.19723,9.54519,48.92825,32.64896,8.12874,7.29078,6.81979,3.66798,8.59550,26.90507,6.75503,1180.72223
3,79.41727,6.21347,68.96604,6.51001,0.0,7.50511,12.25282,5.86831,62.29731,46.70415,6.16562,6.22286,5.89494,1.31032,4.73406,15.64361,6.28720,1189.03640
4,-42.19667,7.54374,61.93949,8.30137,1.0,9.69502,-21.41222,8.29495,59.37862,63.63985,7.72333,6.87700,6.91034,3.22987,6.84112,23.39633,9.48057,1196.65927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12153,85.83334,8.85382,63.05060,6.52608,1.0,5.57966,20.88197,8.19699,45.45344,50.83945,8.07550,7.51521,7.21934,4.14434,8.20927,-6.06727,8.25459,1161.56385
12154,-74.96933,9.57076,74.59498,6.40989,1.0,7.46766,39.71734,10.22643,62.28525,44.65016,7.44350,9.58939,6.21237,20.31640,6.93059,9.98413,7.16850,1111.96189
12155,-73.20483,8.04112,58.35228,8.00848,0.0,7.79391,41.16704,6.13267,57.02437,59.65994,8.55219,6.69683,7.23604,3.27969,9.47929,28.03116,8.20682,1162.90322
12156,-75.23266,6.40452,67.80306,6.61265,1.0,8.99481,43.10090,8.55004,38.08157,28.70273,7.60637,8.09596,8.33362,5.19268,5.97208,40.30525,7.19649,1198.87578
12157,-5.22126,5.23341,60.28862,5.58981,1.0,7.74560,33.43443,5.91521,36.83592,30.23330,7.71321,8.48164,7.11669,7.34125,5.47806,24.29609,8.66348,1054.76897

In [15]:
stations = pd.read_csv('./data/stations.csv',delimiter='\t')
stations

,code,latitude,revision,longitude,location,QoS
0,FR,43.67681,2014/08/22,4.63031,Europe/Paris,accep
1,GB,55.82737,01 Nov 2019,-4.05730,Europe/London,excellent
2,SK,48.43174,"08/08/2017, 00:00:00",17.80310,Europe/Bratislava,accep
3,IT,40.53123,"11/11/2013, 00:00:00",17.58522,Europe/Rome,maitennce
4,CN,35.85000,"09/06/2013, 00:00:00",117.70000,Asia/Shanghai,maintenance
...,...,...,...,...,...,...
1017,US,33.50921,"12/20/2019, 00:00:00",-111.89903,America/Phoenix,good
1018,DE,50.23019,"11/02/2013, 00:00:00",8.77155,Europe/Berlin,average
1019,GB,51.62907,"12/03/2019, 00:00:00",-0.74934,Europe/London,average
1020,RU,55.64776,2019/04/10,38.02486,Europe/Moscow,building
1021,PE,-16.25000,2016/12/27,-69.08333,America/Lima,maintenance

In [21]:
stations.groupby('QoS').count() #Accep a Acceptable budú pravdepodobne rovnaké hodnoty ako aj maintenance a maitennce

             code  latitude  revision  longitude  location
QoS
accep         202       202       202        202       202
acceptable      3         3         3          3         3
average       205       205       205        205       205
building       97        97        97         97        97
excellent     199       199       199        199       199
good          198       198       198        198       198
maintenance   110       110       110        110       110
maitennce       8         8         8          8         8

Pravedepodbne v stations treba zmenit aj dátumy, ktoré majú aj hodinové záznamy iba na date